import React, { useState } from "react";
import Head from "next/head";
import MainLayout from "@/layouts/MainLayout";
import { useRouter } from "next/router";
import { FiArrowLeft } from "react-icons/fi";

function DetailProduct(props) {
  const [data, setData] = useState(props?.data ?? {});
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Products | {router.query.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <div className="w-full h-full bg-[#f4f4f4] mt-[28px] md:p-8 p-3">
            <div className="rounded-md bg-white p-3">
              <div className="flex flex-row items-center mb-4 cursor-pointer">
                <button
                  onClick={(event) => {
                    event.preventDefault();
                    router.back();
                  }}
                  className="bg-[#f4f4f4] p-2 rounded-md"
                >
                  <FiArrowLeft />
                </button>
                <h1 className="text-xl font-bold text-[#11142D] ml-2">
                  Product Detail
                </h1>
              </div>
            </div>
          </div>
        </MainLayout>
      </main>
    </>
  );
}

export async function getServerSideProps(props) {
  const fetchProductId = await fetch(
    `http://localhost:8080/product/show/${props.params.id}`
  );
  const data = await fetchProductId.json();
  console.log("Data: ", data);
  return {
    props: {
      data: data,
    },
  };
}

export default DetailProduct;
