// import Modal from '@/components/Modal'
import ProductItem from "@/components/ProductItem";
import MainLayout from "@/layouts/MainLayout";
import Head from "next/head";
import { useEffect } from "react";

export default function Products(props) {
  useEffect(() => {
    console.log("Data: ", props.data);
  }, []);
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <div className="w-full h-full bg-[#f4f4f4] mt-[28px] md:p-8 p-3">
            <div className="rounded-md bg-white p-3">
              <h1 className="mb-4 text-xl font-bold text-[#11142D]">
                Products List
              </h1>
              <div className="divide-y gap-y-2">
                {props?.data?.data?.map((item, index) => {
                  return (
                    <ProductItem
                      key={`index-${item._id}`}
                      price={item.price}
                      name={item.name}
                      category={item.category.name}
                      status={item.status}
                      stock={item.quantity}
                      productId={item._id}
                    />
                  );
                })}
              </div>
            </div>
          </div>
        </MainLayout>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const resData = await fetch("http://localhost:8080/product/show", {
    headers: {
      authorization:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDAyYmZjMjYxNmNhODJmZDRiMjlmODYiLCJpYXQiOjE2Nzc5MDE3OTd9.6IJ42R6Ns30OvRwpE0EEeVZ6p5h_3snFDlE_yfWwQd8",
    },
  });
  const data = await resData.json();

  return {
    props: {
      data: data,
    },
  };
}
