// import Modal from '@/components/Modal'
import MainLayout from '@/layouts/MainLayout'
import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <MainLayout>
          <div className='h-full bg-[#F4F4F4] mt-[28px] md:mx-0 mx-4'>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
            <p>Dashboard</p>
          </div>
        </MainLayout>
      </main>
    </>
  )
}
